/*
 * TB_MEMBER (회원정보)
 */
DROP TABLE `quiz`.`tb_member`;
CREATE TABLE `quiz`.`tb_member` (
  `member_no` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `member_type` VARCHAR(12) NOT NULL DEFAULT 'USER',
  `state_cd` VARCHAR(12) NOT NULL DEFAULT 'ACTIVATION',
  `last_pwd_changed_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creator` INT(10) UNSIGNED NOT NULL,
  `updater` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_no`))
;